AllCops:
  TargetRubyVersion: 3.1.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
   Enabled: False

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Metrics/ClassLength:
  Max: 150
